name = "getchitty"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "get.chitty.cc/*", zone_name = "chitty.cc" }
]

[env.staging]
routes = [
  { pattern = "get-staging.chitty.cc/*", zone_name = "chitty.cc" }
]
